repos:
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
    -   id: mypy
        name: Mypy
        entry: ./run-mypy
        language: python
-   repo: https://github.com/psf/black
    rev: 21.8b0
    hooks:
    -   id: black
